# Generated by Django 2.0.4 on 2018-04-21 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainClusterSearchConfiguration',
            fields=[
                ('domain', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('domain_base_url', models.TextField()),
                ('crawled_page_dir', models.TextField()),
                ('file_of_urlmaps', models.TextField()),
                ('solr_base_url', models.TextField()),
                ('solr_collection_name', models.TextField()),
                ('solr_collection_num_shards', models.IntegerField(default=2)),
                ('solr_collection_rep_factor', models.IntegerField(default=2)),
                ('solr_collection_max_shards_per_node', models.IntegerField(default=2)),
                ('solr_collection_configset', models.TextField(default='cluster_configs')),
                ('semantic_search_field', models.CharField(default='_text_', max_length=250)),
                ('mysql_host', models.CharField(default='localhost', max_length=250)),
                ('mysql_port', models.IntegerField(default='8888')),
                ('mysql_unix_socket', models.TextField(default='/tmp/mysql.sock')),
                ('mysql_user', models.TextField(default='root')),
                ('mysql_password', models.TextField(default='')),
                ('mysql_database', models.TextField(default='test')),
                ('mysql_similarity_table', models.CharField(default='all_page_similarities', max_length=100)),
                ('last_updated', models.DateTimeField(verbose_name='last updated')),
            ],
        ),
        migrations.CreateModel(
            name='DomainClusterSearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster_search.DomainClusterSearchConfiguration')),
            ],
        ),
    ]
