# Generated by Django 2.0.4 on 2018-04-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainclustersearchconfiguration',
            old_name='crawled_page_dir',
            new_name='crawled_page_output_dir',
        ),
        migrations.AlterField(
            model_name='domainclustersearchconfiguration',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='domainclustersearchconfiguration',
            name='mysql_database',
            field=models.CharField(default='test', max_length=255),
        ),
        migrations.AlterField(
            model_name='domainclustersearchconfiguration',
            name='mysql_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='domainclustersearchconfiguration',
            name='mysql_user',
            field=models.CharField(default='root', max_length=255),
        ),
        migrations.AlterField(
            model_name='domainclustersearchconfiguration',
            name='solr_collection_configset',
            field=models.CharField(default='cluster_configs', max_length=255),
        ),
        migrations.AlterField(
            model_name='domainclustersearchconfiguration',
            name='solr_collection_name',
            field=models.CharField(max_length=255),
        ),
    ]
