# Generated by Django 2.0.4 on 2018-04-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_search', '0002_auto_20180421_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainclustersearchquery',
            name='cluster_algorithm',
            field=models.CharField(choices=[('dbscan', 'dbscan'), ('linkage-single', 'linkage-single'), ('linkage-complete', 'linkage-complete'), ('linkage-average', 'linkage-average'), ('linkage-weighted', 'linkage-weighted'), ('linkage-centroid', 'linkage-centroid'), ('linkage-median', 'linkage-median'), ('linkage-ward', 'linkage-ward')], default='dbscan', max_length=50),
        ),
    ]
