# Generated by Django 2.0.4 on 2018-04-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_search', '0003_domainclustersearchquery_cluster_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainclustersearchquery',
            name='rank_algorithm',
            field=models.CharField(choices=[('max_score', 'max_score')], default='max_score', max_length=100),
        ),
        migrations.AddField(
            model_name='domainclustersearchquery',
            name='summary_algorithm',
            field=models.CharField(choices=[('rake', 'rake')], default='rake', max_length=100),
        ),
        migrations.AlterField(
            model_name='domainclustersearchquery',
            name='cluster_algorithm',
            field=models.CharField(choices=[('dbscan', 'dbscan'), ('linkage-single', 'linkage-single'), ('linkage-complete', 'linkage-complete'), ('linkage-average', 'linkage-average'), ('linkage-weighted', 'linkage-weighted'), ('linkage-centroid', 'linkage-centroid'), ('linkage-median', 'linkage-median'), ('linkage-ward', 'linkage-ward')], default='dbscan', max_length=100),
        ),
    ]
