# Generated by Django 2.0.4 on 2018-04-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_search', '0004_auto_20180424_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainclustersearchconfiguration',
            name='semantic_search_field',
            field=models.CharField(default='_plaintext_', max_length=250),
        ),
    ]
